-- Investor-grade flip analytics: transaction comparables, all-in scenarios,
-- liquidity, risk, offer history, duplicate detection and rental fallback.

create table if not exists public.market_transactions (
  transaction_id text primary key,
  city_key text not null,
  city text not null,
  voivodeship text not null,
  transaction_date date,
  address text,
  area numeric,
  price integer,
  price_m2 numeric,
  market_type text,
  transaction_type text,
  latitude numeric,
  longitude numeric,
  source_name text not null default 'GUGiK RCN WFS',
  source_url text,
  fetched_at timestamptz not null default now()
);

create table if not exists public.rent_market_stats (
  city_key text not null,
  city text not null,
  voivodeship text not null,
  median_rent_m2 numeric,
  median_monthly_rent numeric,
  sample_count integer not null default 0,
  sample_offers jsonb not null default '[]'::jsonb,
  source_name text not null,
  source_url text,
  fetched_at timestamptz not null default now(),
  primary key (city_key, voivodeship)
);

create table if not exists public.offer_price_history (
  id bigint generated by default as identity primary key,
  source text not null,
  source_offer_id text not null,
  price integer not null,
  area numeric,
  price_m2 numeric,
  url text,
  seen_at timestamptz not null default now()
);

create index if not exists market_transactions_location_date_idx
  on public.market_transactions (voivodeship, city_key, transaction_date desc);
create index if not exists market_transactions_location_area_idx
  on public.market_transactions (voivodeship, city_key, area);
create index if not exists rent_market_stats_fetched_idx
  on public.rent_market_stats (fetched_at desc);
create unique index if not exists offer_price_history_unique_price_idx
  on public.offer_price_history (source, source_offer_id, price);
create index if not exists offer_price_history_offer_seen_idx
  on public.offer_price_history (source, source_offer_id, seen_at);

alter table public.market_transactions enable row level security;
alter table public.rent_market_stats enable row level security;
alter table public.offer_price_history enable row level security;
revoke all on public.market_transactions, public.rent_market_stats, public.offer_price_history from anon, authenticated;
grant all on public.market_transactions, public.rent_market_stats, public.offer_price_history to service_role;
grant usage, select on all sequences in schema public to service_role;

alter table public.source_candidates
  add column if not exists initial_price integer,
  add column if not exists price_change_count integer not null default 0,
  add column if not exists price_change_pct numeric,
  add column if not exists days_on_market integer,
  add column if not exists offer_fingerprint text,
  add column if not exists duplicate_count integer not null default 1,
  add column if not exists duplicate_sources text[] not null default '{}'::text[],
  add column if not exists comparable_transactions jsonb not null default '[]'::jsonb,
  add column if not exists comparable_count integer not null default 0,
  add column if not exists comparable_median_price_m2 numeric,
  add column if not exists sale_price_fast integer,
  add column if not exists sale_price_base integer,
  add column if not exists sale_price_optimistic integer,
  add column if not exists acquisition_costs integer,
  add column if not exists holding_costs integer,
  add column if not exists selling_costs integer,
  add column if not exists total_investment integer,
  add column if not exists net_profit_fast integer,
  add column if not exists net_profit_base integer,
  add column if not exists net_profit_optimistic integer,
  add column if not exists roi_fast numeric,
  add column if not exists roi_base numeric,
  add column if not exists roi_optimistic numeric,
  add column if not exists liquidity_score integer,
  add column if not exists estimated_sale_days integer,
  add column if not exists liquidity_note text,
  add column if not exists risk_score integer,
  add column if not exists risk_level text,
  add column if not exists risk_flags text[] not null default '{}'::text[],
  add column if not exists risk_note text,
  add column if not exists condition_score integer,
  add column if not exists renovation_scope text,
  add column if not exists renovation_cost_base integer,
  add column if not exists photo_count integer not null default 0,
  add column if not exists image_urls text[] not null default '{}'::text[],
  add column if not exists photo_analysis_note text,
  add column if not exists monthly_rent_estimate integer,
  add column if not exists rental_yield_gross numeric,
  add column if not exists rental_yield_net numeric,
  add column if not exists rent_sample_count integer,
  add column if not exists rent_fallback_note text,
  add column if not exists market_trend_3m_pct numeric,
  add column if not exists market_trend_12m_pct numeric,
  add column if not exists alert_tier text,
  add column if not exists investment_summary text,
  add column if not exists analysis_version text,
  add column if not exists calculations_updated_at timestamptz;

alter table public.offers
  add column if not exists initial_price integer,
  add column if not exists price_change_count integer not null default 0,
  add column if not exists price_change_pct numeric,
  add column if not exists days_on_market integer,
  add column if not exists offer_fingerprint text,
  add column if not exists duplicate_count integer not null default 1,
  add column if not exists duplicate_sources text[] not null default '{}'::text[],
  add column if not exists comparable_transactions jsonb not null default '[]'::jsonb,
  add column if not exists comparable_count integer not null default 0,
  add column if not exists comparable_median_price_m2 numeric,
  add column if not exists sale_price_fast integer,
  add column if not exists sale_price_base integer,
  add column if not exists sale_price_optimistic integer,
  add column if not exists acquisition_costs integer,
  add column if not exists holding_costs integer,
  add column if not exists selling_costs integer,
  add column if not exists total_investment integer,
  add column if not exists net_profit_fast integer,
  add column if not exists net_profit_base integer,
  add column if not exists net_profit_optimistic integer,
  add column if not exists roi_fast numeric,
  add column if not exists roi_base numeric,
  add column if not exists roi_optimistic numeric,
  add column if not exists liquidity_score integer,
  add column if not exists estimated_sale_days integer,
  add column if not exists liquidity_note text,
  add column if not exists risk_score integer,
  add column if not exists risk_level text,
  add column if not exists risk_flags text[] not null default '{}'::text[],
  add column if not exists risk_note text,
  add column if not exists condition_score integer,
  add column if not exists renovation_scope text,
  add column if not exists renovation_cost_base integer,
  add column if not exists photo_count integer not null default 0,
  add column if not exists image_urls text[] not null default '{}'::text[],
  add column if not exists photo_analysis_note text,
  add column if not exists monthly_rent_estimate integer,
  add column if not exists rental_yield_gross numeric,
  add column if not exists rental_yield_net numeric,
  add column if not exists rent_sample_count integer,
  add column if not exists rent_fallback_note text,
  add column if not exists market_trend_3m_pct numeric,
  add column if not exists market_trend_12m_pct numeric,
  add column if not exists alert_tier text,
  add column if not exists investment_summary text,
  add column if not exists analysis_version text,
  add column if not exists calculations_updated_at timestamptz;

create index if not exists source_candidates_flip_tier_idx
  on public.source_candidates (flip_match, alert_tier, last_seen_at desc);
create index if not exists source_candidates_fingerprint_idx
  on public.source_candidates (offer_fingerprint);

create or replace function public.log_source_candidate_price()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.price is not null and (tg_op = 'INSERT' or old.price is distinct from new.price) then
    insert into public.offer_price_history(source, source_offer_id, price, area, price_m2, url, seen_at)
    values (new.source, new.source_offer_id, new.price, new.area, new.price_m2, new.url, coalesce(new.last_seen_at, now()))
    on conflict (source, source_offer_id, price) do nothing;
  end if;
  return new;
end;
$$;

revoke all on function public.log_source_candidate_price() from public, anon, authenticated;
grant execute on function public.log_source_candidate_price() to service_role;
drop trigger if exists source_candidate_price_history on public.source_candidates;
create trigger source_candidate_price_history
after insert or update of price on public.source_candidates
for each row execute function public.log_source_candidate_price();

insert into public.offer_price_history(source, source_offer_id, price, area, price_m2, url, seen_at)
select source, source_offer_id, price, area, price_m2, url, first_seen_at
from public.source_candidates
where price is not null
on conflict (source, source_offer_id, price) do nothing;

drop function if exists public.recompute_flip_analysis();

create function public.recompute_flip_analysis()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer := 0;
begin
  -- Extract condition, amenity and legal/technical risk signals from each listing.
  with signals as (
    select c.id,
      lower(concat_ws(' ', c.title, c.description, c.floor_text)) as txt,
      array_remove(array[
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(lokator|najemca|umowa najmu)' then 'lokator/najemca' end,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(^|[^a-ząćęłńóśźż])udział([^a-ząćęłńóśźż]|$)' then 'udział w nieruchomości' end,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(bez księgi|brak księgi|nieuregulowan.{0,12}(stan|księg))' then 'brak lub niejasna KW' end,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(służebno|dożywoci)' then 'służebność/dożywocie' end,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(licytacj.{0,20}komorn|komornicz)' then 'licytacja komornicza' end,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(wilgoć|wilgoci|grzyb|zagrzyb|pęknięci)' then 'wilgoć/grzyb/pęknięcia' end,
        case when lower(concat_ws(' ', c.title, c.description, c.floor_text)) ~ '(suterena|piwnic)' then 'suterena/piwnica' end,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(piec kaflow|ogrzewanie piec)' then 'ogrzewanie piecowe' end,
        case when c.price is null or c.area is null or c.city is null or lower(c.city) = 'nieustalona' then 'braki danych podstawowych' end
      ], null)::text[] as flags,
      least(100,
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(lokator|najemca|umowa najmu)' then 30 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(^|[^a-ząćęłńóśźż])udział([^a-ząćęłńóśźż]|$)' then 35 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(bez księgi|brak księgi|nieuregulowan.{0,12}(stan|księg))' then 25 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(służebno|dożywoci)' then 35 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(licytacj.{0,20}komorn|komornicz)' then 25 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(wilgoć|wilgoci|grzyb|zagrzyb|pęknięci)' then 15 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description, c.floor_text)) ~ '(suterena|piwnic)' then 10 else 0 end +
        case when lower(concat_ws(' ', c.title, c.description)) ~ '(piec kaflow|ogrzewanie piec)' then 5 else 0 end +
        case when c.price is null or c.area is null or c.city is null or lower(c.city) = 'nieustalona' then 25 else 0 end
      )::integer as risk,
      case
        when lower(concat_ws(' ', c.title, c.description)) ~ '(po generalnym remoncie|po kapitalnym remoncie|wyremontowan|gotow.{0,10}do zamieszkania|nowe wykończenie)' then 'gotowe / po remoncie'
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do odświeżenia|odswiezenia|częściowego remontu|drobnego remontu)' then 'odświeżenie'
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do generalnego remontu|do kapitalnego remontu|do remontu|stan surowy)' then 'generalny remont'
        else 'stan nieustalony — rezerwa konserwatywna'
      end as scope,
      case
        when lower(concat_ws(' ', c.title, c.description)) ~ '(po generalnym remoncie|po kapitalnym remoncie|wyremontowan|gotow.{0,10}do zamieszkania|nowe wykończenie)' then 85
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do odświeżenia|odswiezenia|częściowego remontu|drobnego remontu)' then 60
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do generalnego remontu|do kapitalnego remontu|do remontu|stan surowy)' then 25
        else 50
      end as condition,
      case
        when lower(concat_ws(' ', c.title, c.description)) ~ '(po generalnym remoncie|po kapitalnym remoncie|wyremontowan|gotow.{0,10}do zamieszkania|nowe wykończenie)' then 500
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do odświeżenia|odswiezenia|częściowego remontu|drobnego remontu)' then 800
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do generalnego remontu|do kapitalnego remontu|do remontu|stan surowy)' then 2050
        else 1300
      end as reno_base_m2,
      case
        when lower(concat_ws(' ', c.title, c.description)) ~ '(po generalnym remoncie|po kapitalnym remoncie|wyremontowan|gotow.{0,10}do zamieszkania|nowe wykończenie)' then 300
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do odświeżenia|odswiezenia|częściowego remontu|drobnego remontu)' then 500
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do generalnego remontu|do kapitalnego remontu|do remontu|stan surowy)' then 1600
        else 900
      end as reno_low_m2,
      case
        when lower(concat_ws(' ', c.title, c.description)) ~ '(po generalnym remoncie|po kapitalnym remoncie|wyremontowan|gotow.{0,10}do zamieszkania|nowe wykończenie)' then 800
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do odświeżenia|odswiezenia|częściowego remontu|drobnego remontu)' then 1100
        when lower(concat_ws(' ', c.title, c.description)) ~ '(do generalnego remontu|do kapitalnego remontu|do remontu|stan surowy)' then 2600
        else 1800
      end as reno_high_m2
    from public.source_candidates c
  )
  update public.source_candidates c set
    has_balcony = coalesce(c.has_balcony, false) or s.txt ~ '(balkon|loggia)',
    has_terrace = coalesce(c.has_terrace, false) or s.txt ~ '(taras)',
    days_on_market = greatest(0, floor(extract(epoch from (now() - c.first_seen_at)) / 86400))::integer,
    offer_fingerprint = md5(lower(coalesce(c.city, '')) || '|' || coalesce(round(c.area * 2) / 2, 0)::text || '|' || coalesce(round(c.price / 5000.0) * 5000, 0)::text),
    risk_flags = s.flags,
    risk_score = s.risk,
    risk_level = case when s.risk >= 60 then 'wysokie' when s.risk >= 30 then 'średnie' else 'niskie' end,
    risk_note = case when cardinality(s.flags) = 0 then 'Brak automatycznie wykrytych czerwonych flag; wymagana weryfikacja KW, zadłużeń i stanu technicznego.' else 'Wykryte sygnały: ' || array_to_string(s.flags, ', ') || '. Wymagana weryfikacja dokumentów i oględziny.' end,
    condition_score = s.condition,
    renovation_scope = s.scope,
    renovation_cost_low = case when c.area is not null then round(c.area * s.reno_low_m2)::integer end,
    renovation_cost_base = case when c.area is not null then round(c.area * s.reno_base_m2)::integer end,
    renovation_cost_high = case when c.area is not null then round(c.area * s.reno_high_m2)::integer end,
    photo_count = coalesce(cardinality(c.image_urls), 0),
    photo_analysis_note = case when coalesce(cardinality(c.image_urls), 0) > 0
      then 'Zdjęcia zapisane do weryfikacji; koszt remontu oszacowano konserwatywnie na podstawie opisu ogłoszenia.'
      else 'Brak zdjęć możliwych do automatycznego pobrania; koszt remontu oszacowano konserwatywnie na podstawie opisu.' end
  from signals s
  where c.id = s.id;

  -- Price history and cross-portal duplicate signals.
  with history as (
    select source, source_offer_id,
      (array_agg(price order by seen_at asc))[1] as initial_price,
      greatest(count(distinct price) - 1, 0)::integer as changes
    from public.offer_price_history
    group by source, source_offer_id
  )
  update public.source_candidates c set
    initial_price = h.initial_price,
    price_change_count = h.changes,
    price_change_pct = case when h.initial_price > 0 and c.price is not null then round(((c.price - h.initial_price)::numeric / h.initial_price) * 100, 1) end
  from history h
  where c.source = h.source and c.source_offer_id = h.source_offer_id;

  with duplicate_groups as (
    select offer_fingerprint, count(*)::integer as duplicate_count, array_agg(distinct source order by source) as sources
    from public.source_candidates
    where offer_fingerprint is not null and price is not null and area is not null
    group by offer_fingerprint
  )
  update public.source_candidates c set duplicate_count = d.duplicate_count, duplicate_sources = d.sources
  from duplicate_groups d where c.offer_fingerprint = d.offer_fingerprint;

  -- The eight closest, recent transactions by city and usable area.
  with ranked as (
    select c.id, t.transaction_id, t.transaction_date, t.address, t.area, t.price, t.price_m2,
      row_number() over (partition by c.id order by abs(t.area - c.area), t.transaction_date desc nulls last) as rn
    from public.source_candidates c
    join public.market_transactions t
      on t.city_key = lower(trim(c.city)) and t.voivodeship = c.voivodeship
     and t.area between c.area - 15 and c.area + 15
     and t.transaction_date >= current_date - interval '2 years'
    where c.area is not null
  ), comps as (
    select id, count(*)::integer as comp_count,
      round(percentile_cont(0.5) within group (order by price_m2)::numeric, 2) as comp_median,
      jsonb_agg(jsonb_build_object('date', transaction_date, 'address', address, 'area', area, 'price', price, 'price_m2', round(price_m2, 0)) order by rn) as details
    from ranked where rn <= 8 group by id
  )
  update public.source_candidates c set
    comparable_count = coalesce(x.comp_count, 0),
    comparable_median_price_m2 = x.comp_median,
    comparable_transactions = coalesce(x.details, '[]'::jsonb)
  from comps x where c.id = x.id;

  update public.source_candidates c set comparable_count = 0, comparable_median_price_m2 = null, comparable_transactions = '[]'::jsonb
  where not exists (select 1 from public.market_transactions t where t.city_key = lower(trim(c.city)) and t.voivodeship = c.voivodeship and t.area between c.area - 15 and c.area + 15);

  -- Local transaction trend, supply/demand liquidity and rental fallback.
  with city_tx as (
    select voivodeship, city_key,
      count(*) filter (where transaction_date >= current_date - interval '12 months')::numeric / 12 as monthly_transactions,
      percentile_cont(0.5) within group (order by price_m2) filter (where transaction_date >= current_date - interval '90 days') as med_3m,
      percentile_cont(0.5) within group (order by price_m2) filter (where transaction_date < current_date - interval '90 days' and transaction_date >= current_date - interval '180 days') as med_prev_3m,
      percentile_cont(0.5) within group (order by price_m2) filter (where transaction_date >= current_date - interval '12 months') as med_12m,
      percentile_cont(0.5) within group (order by price_m2) filter (where transaction_date < current_date - interval '12 months' and transaction_date >= current_date - interval '24 months') as med_prev_12m
    from public.market_transactions group by voivodeship, city_key
  ), supply as (
    select voivodeship, lower(trim(city)) as city_key, count(*)::numeric as active_supply
    from public.source_candidates
    where last_seen_at >= now() - interval '30 days' and price is not null and area between 25 and 60
    group by voivodeship, lower(trim(city))
  ), metrics as (
    select c.id,
      greatest(30, least(180, round(30 * coalesce(s.active_supply, 1) / greatest(coalesce(t.monthly_transactions, 1), 1))))::integer as sale_days,
      case when t.med_prev_3m > 0 then round(((t.med_3m - t.med_prev_3m) / t.med_prev_3m * 100)::numeric, 1) end as trend_3m,
      case when t.med_prev_12m > 0 then round(((t.med_12m - t.med_prev_12m) / t.med_prev_12m * 100)::numeric, 1) end as trend_12m,
      r.median_rent_m2, r.sample_count as rent_count
    from public.source_candidates c
    left join city_tx t on t.voivodeship = c.voivodeship and t.city_key = lower(trim(c.city))
    left join supply s on s.voivodeship = c.voivodeship and s.city_key = lower(trim(c.city))
    left join public.rent_market_stats r on r.voivodeship = c.voivodeship and r.city_key = lower(trim(c.city))
  )
  update public.source_candidates c set
    estimated_sale_days = m.sale_days,
    liquidity_score = greatest(0, least(100, round(100 - ((m.sale_days - 30) * 100.0 / 150))))::integer,
    liquidity_note = case when m.sale_days <= 60 then 'Wysoka płynność: szacowana ekspozycja 30–60 dni.' when m.sale_days <= 105 then 'Średnia płynność: szacowana ekspozycja 2–3,5 miesiąca.' else 'Niższa płynność: szacowana ekspozycja powyżej 3,5 miesiąca.' end,
    market_trend_3m_pct = m.trend_3m,
    market_trend_12m_pct = m.trend_12m,
    monthly_rent_estimate = case when m.median_rent_m2 is not null and c.area is not null then round(m.median_rent_m2 * c.area)::integer end,
    rent_sample_count = m.rent_count,
    rent_fallback_note = case when m.median_rent_m2 is not null then 'Plan B: czynsz najmu oszacowany z bieżących ofert w tej lokalizacji; przed zakupem sprawdź czynsz administracyjny i pustostan.' else 'Brak wystarczającej próby najmu dla tej lokalizacji.' end
  from metrics m where c.id = m.id;

  -- Three sale scenarios and a transparent 100-point investment score.
  with basis as (
    select c.*,
      coalesce(case when c.comparable_count >= 3 then c.comparable_median_price_m2 end, s.median_transaction_price_m2) as benchmark_m2,
      coalesce(case when c.comparable_count >= 3 then c.comparable_count end, s.sample_count, 0) as benchmark_count
    from public.source_candidates c
    left join public.market_transaction_stats s on s.city_key = lower(trim(c.city)) and s.voivodeship = c.voivodeship
  ), scenarios as (
    select b.*,
      case when benchmark_m2 is not null and area is not null then round(benchmark_m2 * area * 0.93)::integer end as fast_sale,
      case when benchmark_m2 is not null and area is not null then round(benchmark_m2 * area * 0.98)::integer end as base_sale,
      case when benchmark_m2 is not null and area is not null then round(benchmark_m2 * area * 1.03)::integer end as optimistic_sale,
      case when price is not null then round(price * 0.02 + 2500)::integer end as acquire_cost,
      case when area is not null then round(greatest(4200, area * 120))::integer end as hold_cost
    from basis b
  ), profits as (
    select s.*,
      case when price is not null and renovation_cost_base is not null then price + acquire_cost + renovation_cost_base + hold_cost end as invested,
      case when base_sale is not null then round(base_sale * 0.03)::integer end as sell_cost
    from scenarios s
  ), calculated as (
    select p.*,
      case when invested is not null and fast_sale is not null then round(fast_sale * 0.97 - invested)::integer end as profit_fast,
      case when invested is not null and base_sale is not null then round(base_sale * 0.97 - invested)::integer end as profit_base,
      case when invested is not null and optimistic_sale is not null then round(optimistic_sale * 0.97 - invested)::integer end as profit_optimistic,
      case when benchmark_m2 > 0 and price_m2 is not null then round(((benchmark_m2 - price_m2) / benchmark_m2 * 100)::numeric, 1) end as discount_pct
    from profits p
  ), scored as (
    select x.*,
      case when invested > 0 then round(profit_fast::numeric / invested * 100, 1) end as pct_fast,
      case when invested > 0 then round(profit_base::numeric / invested * 100, 1) end as pct_base,
      case when invested > 0 then round(profit_optimistic::numeric / invested * 100, 1) end as pct_optimistic,
      round(
        least(30, greatest(0, coalesce((profit_base::numeric / nullif(invested, 0) * 100) / 35 * 30, 0))) +
        least(20, greatest(0, coalesce((discount_pct - 20) / 40 * 20, 0))) +
        coalesce(liquidity_score, 0) / 100.0 * 20 +
        (100 - coalesce(risk_score, 50)) / 100.0 * 15 +
        least(10, benchmark_count / 8.0 * 10) +
        case when has_terrace then 5 when has_balcony then 3 else 0 end
      )::integer as new_score
    from calculated x
  )
  update public.source_candidates c set
    market_price_m2 = round(s.benchmark_m2, 2),
    market_discount_pct = s.discount_pct,
    market_basis = case when s.comparable_count >= 3 then 'GUGiK RCN — transakcje porównawcze o zbliżonym metrażu' when s.benchmark_m2 is not null then 'GUGiK RCN — mediana transakcyjna dla miasta' else 'brak wystarczających danych transakcyjnych RCN' end,
    transaction_sample_count = s.benchmark_count,
    sale_price_fast = s.fast_sale,
    sale_price_base = s.base_sale,
    sale_price_optimistic = s.optimistic_sale,
    suggested_sale_price = s.base_sale,
    suggested_purchase_price = null,
    acquisition_costs = s.acquire_cost,
    holding_costs = s.hold_cost,
    selling_costs = s.sell_cost,
    total_investment = s.invested,
    net_profit_fast = s.profit_fast,
    net_profit_base = s.profit_base,
    net_profit_optimistic = s.profit_optimistic,
    estimated_profit_low = s.profit_fast,
    estimated_profit_high = s.profit_optimistic,
    roi_fast = s.pct_fast,
    roi_base = s.pct_base,
    roi_optimistic = s.pct_optimistic,
    rental_yield_gross = case when s.monthly_rent_estimate is not null and s.invested > 0 then round((s.monthly_rent_estimate * 12.0 / s.invested * 100)::numeric, 1) end,
    rental_yield_net = case when s.monthly_rent_estimate is not null and s.invested > 0 then round((s.monthly_rent_estimate * 12.0 * 0.72 / s.invested * 100)::numeric, 1) end,
    analysis_confidence = case when s.benchmark_count >= 8 then 'wysoka' when s.benchmark_count >= 3 then 'średnia' else 'niska' end,
    flip_score = greatest(0, least(100, s.new_score)),
    alert_tier = case when s.new_score >= 80 then 'A' when s.new_score >= 65 then 'B' else 'C' end,
    score_note = 'Wagi: ROI 30, rabat 20, płynność 20, ryzyko 15, dane RCN 10, balkon/taras 5.',
    investment_summary = case when s.profit_base is null then 'Brak danych do pełnej kalkulacji.' else 'Scenariusz bazowy: zysk netto przed podatkiem ' || to_char(s.profit_base, 'FM999G999G999') || ' zł, ROI ' || coalesce(s.pct_base::text, '?') || '%.' end,
    analysis_note = 'Koszty all-in obejmują zakup, orientacyjny PCC/notariusza, remont, 6-miesięczny bufor utrzymania i 3% koszt sprzedaży. Wynik jest przed podatkiem dochodowym i finansowaniem.',
    analysis_version = 'investor-v2.0',
    calculations_updated_at = now(),
    flip_match = coalesce(s.voivodeship in ('śląskie', 'opolskie') and s.price <= 350000 and s.area between 25 and 60 and s.discount_pct >= 30 and s.profit_base > 0 and coalesce(s.risk_score, 0) < 75, false)
  from scored s where c.id = s.id;

  get diagnostics affected = row_count;

  -- Keep the legacy offers table aligned for compatibility with older workflows.
  update public.offers o set
    market_price_m2=c.market_price_m2, market_discount_pct=c.market_discount_pct,
    renovation_cost_low=c.renovation_cost_low, renovation_cost_base=c.renovation_cost_base, renovation_cost_high=c.renovation_cost_high,
    suggested_sale_price=c.suggested_sale_price, suggested_purchase_price=null,
    estimated_profit_low=c.estimated_profit_low, estimated_profit_high=c.estimated_profit_high,
    analysis_confidence=c.analysis_confidence, analysis_note=c.analysis_note, has_balcony=c.has_balcony, has_terrace=c.has_terrace,
    flip_score=c.flip_score, score_note=c.score_note, market_basis=c.market_basis, transaction_sample_count=c.transaction_sample_count,
    initial_price=c.initial_price, price_change_count=c.price_change_count, price_change_pct=c.price_change_pct, days_on_market=c.days_on_market,
    offer_fingerprint=c.offer_fingerprint, duplicate_count=c.duplicate_count, duplicate_sources=c.duplicate_sources,
    comparable_transactions=c.comparable_transactions, comparable_count=c.comparable_count, comparable_median_price_m2=c.comparable_median_price_m2,
    sale_price_fast=c.sale_price_fast, sale_price_base=c.sale_price_base, sale_price_optimistic=c.sale_price_optimistic,
    acquisition_costs=c.acquisition_costs, holding_costs=c.holding_costs, selling_costs=c.selling_costs, total_investment=c.total_investment,
    net_profit_fast=c.net_profit_fast, net_profit_base=c.net_profit_base, net_profit_optimistic=c.net_profit_optimistic,
    roi_fast=c.roi_fast, roi_base=c.roi_base, roi_optimistic=c.roi_optimistic,
    liquidity_score=c.liquidity_score, estimated_sale_days=c.estimated_sale_days, liquidity_note=c.liquidity_note,
    risk_score=c.risk_score, risk_level=c.risk_level, risk_flags=c.risk_flags, risk_note=c.risk_note,
    condition_score=c.condition_score, renovation_scope=c.renovation_scope, photo_count=c.photo_count, image_urls=c.image_urls, photo_analysis_note=c.photo_analysis_note,
    monthly_rent_estimate=c.monthly_rent_estimate, rental_yield_gross=c.rental_yield_gross, rental_yield_net=c.rental_yield_net, rent_sample_count=c.rent_sample_count, rent_fallback_note=c.rent_fallback_note,
    market_trend_3m_pct=c.market_trend_3m_pct, market_trend_12m_pct=c.market_trend_12m_pct,
    alert_tier=c.alert_tier, investment_summary=c.investment_summary, analysis_version=c.analysis_version, calculations_updated_at=c.calculations_updated_at
  from public.source_candidates c
  where o.source=c.source and o.source_offer_id=c.source_offer_id;

  return affected;
end;
$$;

revoke all on function public.recompute_flip_analysis() from public, anon, authenticated;
grant execute on function public.recompute_flip_analysis() to service_role;
